### ISSUE TITLE
Documentation for browser support

### ISSUE THREAD

**Issue by RyKilleen** [tomhodgins/cssplus#1]
Does this project's browser support map directly to CSS Variable support? Does it attempt to polyfill anything? A brief comment of "Evergreen browser support only" would go a long way.

Looks like a cool project, excited to take it for a spin!

**Comment by tomhodgins** [comment]
Hi @RyKilleen! Thanks for the question, right now everything is still shifting around with development quite a bit so I'm not even sure what the extent of browser support is yet.

Without transpilation (from ES6  -> ES5) the plugins appear to work in all browsers that support CSS variables _except_ Mobile Safari on iOS9 which doesn't support arrow notation for functions (like `() => {}` instead of `function() {}`).

With transpilation (using Babel), the plugins appear to work in iOS9 though, so I think that should be everywhere CSS variables are supported.

Plugins like 'Selectory' and a couple others I have planned (like the [`--aspect-ratio` property idea](http://codepen.io/tomhodgins/pen/XRZRrZ)) don't even use CSS variables though, so those would run in all the same browsers that support ES6 without transpilation, and with being transpiled may support some browsers that don't support CSS variables (reaching back a little further).

Once things are a little more fleshed out I'll do some better browser testing and update the README :D
